from librosa import note_to_hz
import numpy as np

FMIN = note_to_hz("C3")
FMAX = note_to_hz("F5")

FRAME_LENGTH_LOG2 = 11
FRAME_LENGTH = 1 << FRAME_LENGTH_LOG2
FRAME_LENGTH_HALF_LOG2 = FRAME_LENGTH_LOG2 - 1
FRAME_LENGTH_HALF = 1 << FRAME_LENGTH_HALF_LOG2
NFREQ = FRAME_LENGTH_HALF + 1
SAMPLE_RATE = 48000
WIN_LENGTH = FRAME_LENGTH // 2
HOP_LENGTH = FRAME_LENGTH // 4
N_THRESHOLDS = 100
BETA_PARAMETER_FIRST = 2.0
BETA_PARAMETER_SECOND = 18.0
BOLTZMANN_PARAMETER = 2.0
RESOLUTION = 0.1
MAX_TRANSITION_RATE = 35.92
SWITCH_PROB = 0.01
NO_TROUGH_PROB = 0.01
SEMITONES_IN_OCTAVE = 12

MIN_PERIOD = int(np.floor(SAMPLE_RATE / FMAX))
MAX_PERIOD = min(int(np.ceil(SAMPLE_RATE / FMIN)), FRAME_LENGTH - WIN_LENGTH - 1)
N_BINS_PER_SEMITONE = int(np.ceil(1.0 / RESOLUTION))
N_PITCH_BINS = int(np.floor(12 * N_BINS_PER_SEMITONE * np.log2(FMAX / FMIN))) + 1
MAX_SEMITONES_PER_FRAME = round(MAX_TRANSITION_RATE * 12 * HOP_LENGTH / SAMPLE_RATE)
TRANSITION_WIDTH = MAX_SEMITONES_PER_FRAME * N_BINS_PER_SEMITONE + 1

THETA = -2.0 * np.pi / FRAME_LENGTH

SCALES = ["Eb:min", "G:min", "C:min", "C#:maj", "B:min", "G:minor"]
