from librosa import note_to_hz
import numpy as np

from constants import *


def generate_vars():
    cpp_content = f"""#pragma once

#include "common_types.hpp"

// generated by python script
constexpr int max_semitones_per_frame = {MAX_SEMITONES_PER_FRAME};
constexpr real_t FMIN = {FMIN:.18e};
constexpr real_t FMAX = {FMAX:.18e};
constexpr unsigned n_bins_per_semitone = {N_BINS_PER_SEMITONE};
constexpr int n_pitch_bins = {N_PITCH_BINS};
constexpr int min_period = {MIN_PERIOD};
constexpr int max_period = {MAX_PERIOD};
constexpr unsigned frame_length_log2 = {FRAME_LENGTH_LOG2};
constexpr unsigned frame_length = {FRAME_LENGTH};
constexpr unsigned frame_length_half_log2 = {FRAME_LENGTH_HALF_LOG2};
constexpr unsigned frame_length_half = {FRAME_LENGTH_HALF};
constexpr unsigned nfreq = {NFREQ};
constexpr real_t sample_rate = {SAMPLE_RATE:.18e};
constexpr real_t resolution = {RESOLUTION:.18e};
constexpr unsigned win_length = {WIN_LENGTH};
constexpr unsigned hop_length = {HOP_LENGTH};
constexpr unsigned n_thresholds = {N_THRESHOLDS};
constexpr real_t beta_parameter_first = {BETA_PARAMETER_FIRST:.18e};
constexpr real_t beta_parameter_second = {BETA_PARAMETER_SECOND:.18e};
constexpr real_t boltzmann_parameter = {BOLTZMANN_PARAMETER:.18e};
constexpr real_t max_transition_rate = {MAX_TRANSITION_RATE:.18e};
constexpr real_t switch_prob = {SWITCH_PROB:.18e};
constexpr real_t no_trough_prob = {NO_TROUGH_PROB:.18e};
constexpr int transition_width = {TRANSITION_WIDTH};
constexpr real_t theta = {THETA:.18e};
"""

    with open("../common/common_constants.generated.hpp", "w") as cpp_file:
        cpp_file.write(cpp_content)
