#pragma once

#include "common_types.hpp"

// generated by python script
constexpr size_t max_semitones_per_frame = 5;
constexpr real_t FMIN = 1.30812782650299312e+02;
constexpr real_t FMAX = 6.98456462866007769e+02;
constexpr size_t n_bins_per_semitone = 10;
constexpr size_t n_pitch_bins = 291;
constexpr size_t min_period = 68;
constexpr size_t max_period = 367;
constexpr size_t frame_length_log2 = 11;
constexpr size_t frame_length = 2048;
constexpr size_t frame_length_half_log2 = 10;
constexpr size_t frame_length_half = 1024;
constexpr size_t nfreq = 1025;
constexpr real_t sample_rate = 4.80000000000000000e+04;
constexpr real_t resolution = 1.00000000000000006e-01;
constexpr size_t win_length = 1024;
constexpr size_t hop_length = 512;
constexpr size_t n_thresholds = 100;
constexpr real_t beta_parameter_first = 2.00000000000000000e+00;
constexpr real_t beta_parameter_second = 1.80000000000000000e+01;
constexpr real_t boltzmann_parameter = 2.00000000000000000e+00;
constexpr real_t max_transition_rate = 3.59200000000000017e+01;
constexpr real_t switch_prob = 1.00000000000000002e-02;
constexpr real_t no_trough_prob = 1.00000000000000002e-02;
constexpr size_t transition_width = 51;
constexpr real_t theta = -3.06796157577128234e-03;
