#pragma once

#include "common_types.hpp"

// generated by python script
constexpr int max_semitones_per_frame = 5;
constexpr real_t FMIN = 1.308127826502993116e+02;
constexpr real_t FMAX = 6.984564628660077688e+02;
constexpr unsigned n_bins_per_semitone = 10;
constexpr int n_pitch_bins = 291;
constexpr int min_period = 68;
constexpr int max_period = 367;
constexpr unsigned frame_length_log2 = 11;
constexpr unsigned frame_length = 2048;
constexpr unsigned frame_length_half_log2 = 10;
constexpr unsigned frame_length_half = 1024;
constexpr unsigned nfreq = 1025;
constexpr real_t sample_rate = 4.800000000000000000e+04;
constexpr real_t resolution = 1.000000000000000056e-01;
constexpr unsigned win_length = 1024;
constexpr unsigned hop_length = 512;
constexpr unsigned n_thresholds = 100;
constexpr real_t beta_parameter_first = 2.000000000000000000e+00;
constexpr real_t beta_parameter_second = 1.800000000000000000e+01;
constexpr real_t boltzmann_parameter = 2.000000000000000000e+00;
constexpr real_t max_transition_rate = 3.592000000000000171e+01;
constexpr real_t switch_prob = 1.000000000000000021e-02;
constexpr real_t no_trough_prob = 1.000000000000000021e-02;
constexpr int transition_width = 51;
constexpr real_t theta = -3.067961575771282340e-03;
